# This is a simple conda build which only succeeds when the built-in tests pass.

name: Conda Test Build 

on: 

  # pip will run pytest, this catches problems 
  # with conda building as an extra step when we commit to master

  push:
    branches:
      - master

  workflow_dispatch:
      
    
jobs:

  conda_build_test_deploy:
    name: Conda Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.cache/pip
            
          key: ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/workflows/resources/conda_build_environment.yml') }}

      - name: Miniconda 
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniconda-version: "latest"
            environment-file: .github/workflows/resources/conda_build_environment.yml
            activate-environment: conda-build
            python-version: ${{ matrix.python-version }}
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Conda build (no upload)
        shell: bash -l {0}
        run: |
            conda config --set anaconda_upload no
            conda-build --channel conda-forge  conda
