name: PYPI wheels macos

on: 
  release:
    types: [created, edited]
  # push:
  #   branches:
  #     - dev


jobs:
  deploy_to_pypi:
    name: ${{matrix.os}} build and deploy on pypi (${{ matrix.python-version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest']
        python-version: ['2.7', '3.7', '3.8']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install gfortran (macos)
      run: |
        brew cask install gfortran

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install numpy
        pip install scipy
        pip install Cython
        pip install delocate
        
    - name: Build the wheel
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
 
      run: |
 
        python setup.py bdist_wheel 
        delocate-wheel -d -w fixed_wheels dist/*whl
        twine upload fixed_wheels/*whl  --skip-existing
